Ls and Cd commands
natalymr/SoftwareDesign pull request #1
Opened 2018-04-06 10:53 UTC by demiurg906

2018-04-19 16:35 UTC, yurii-litvinov requested changes
Да, в целом всё так, но хочется ещё комментарии и юнит-тесты (сами же обратили внимание на отсутствие документации). Я понимаю, что в чужой монастырь со своим стайлгайдом и юнит-тестами не ходят, но обычно пуллреквесты без юнит-тестов в хороших open source-проектах даже не рассматриваются.

И заодно, если это не сложно, поправьте падение всего шелла при ошибке команды --- сейчас попытка сделать cd или ls несуществующей папки убивает весь шелл вообще. Наверное, такого рода ошибки должен обрабатывать основной цикл, но раз он этого пока не делает, пусть хоть сами Ваши команды ловят исключения.

2018-05-08 16:54 UTC, demiurg906 commented
@yurii-litvinov, поправил

2018-05-27 08:36 UTC, yurii-litvinov approved these changes
Комментарии так и не появились, но ладно, зачтена

2018-05-27 08:36 UTC, yurii-litvinov commented on utilities.py
> +    except Exception:
Вообще, лучше ловить более специфичное исключение, потому как, например, если в массиве нет нулевого элемента, лучше упасть, а не сказать, что нет такого файла

2018-05-27 08:41 UTC, closed without merging